//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nastolka
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormKyrsov
    {
        public int Id { get; set; }
        public string IdKyrs { get; set; }
        public int IdVremeni { get; set; }
        public string Ydostoverenie { get; set; }
        public string IdPrepod { get; set; }
        public string IdYchenik { get; set; }
    
        public virtual Akaynt Akaynt { get; set; }
        public virtual Kyrsi Kyrsi { get; set; }
        public virtual Prepod Prepod { get; set; }
        public virtual Ycheniki Ycheniki { get; set; }
    }
}
