//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nastolka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kyrsi
    {
        public int Id { get; set; }
        public string NameKyrsa { get; set; }
        public int Vremia { get; set; }
    
        public virtual FormKyrsov FormKyrsov { get; set; }
        public virtual Prepod Prepod { get; set; }
        public virtual Ycheniki Ycheniki { get; set; }
    }
}
