//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nastolka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NastolinoePrilogenieEntities : DbContext
    {
        public NastolinoePrilogenieEntities()
            : base("name=NastolinoePrilogenieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akaynt> Akaynt { get; set; }
        public virtual DbSet<FormKyrsov> FormKyrsov { get; set; }
        public virtual DbSet<Kyrsi> Kyrsi { get; set; }
        public virtual DbSet<Prepod> Prepod { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ycheniki> Ycheniki { get; set; }
    }
}
